version: "3.1"

services:
    postgres:
        container_name: sentry_postgres
        image: postgres
        env_file: 
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        expose:
            - "5432"
        labels:
            - traefik.enable=false
        environment:
            - DB_PASSWORD=${DB_PASSWORD}
        restart: always

    redis:
        container_name: sentry_redis
        image: redis
        expose:
            - "6379"
        labels:
            - traefik.enable=false
        restart: always

    sentry:
        image: sentry
        container_name: sentry_sentry
        env_file: .env
        expose:
            - "9000"
        labels:
            - traefik.enable=false
        environment:
            - SENTRY_SECRET_KEY=${SECRET_KEY}
            - SENTRY_POSTGRES_HOST=${DB_HOST}
            - SENTRY_DB_USER=${DB_USER}
            - SENTRY_DB_PASSWORD=${DB_PASSWORD}
            - SENTRY_REDIS_HOST=${REDIS_HOST}
            - SENTRY_EMAIL_PORT=${SMTP_PORT}
            - SENTRY_EMAIL_HOST=${SMTP_HOST}
            - SENTRY_SERVER_EMAIL=${SMTP_EMAIL}
            - SENTRY_EMAIL_USER=${SMTP_USER}
            - SENTRY_EMAIL_PASSWORD=${SMTP_PASSWORD}
            - SENTRY_EMAIL_USE_TLS=${SMTP_USE_TLS}
        restart: unless-stopped

    web:
        build: .
        container_name: sentry_web
        volumes:
            - nginx_logs:/var/log/nginx
        networks:
            - default
            - reverse-proxy
        labels:
            - traefik.backend=sentry
            - traefik.frontend.rule=Host:sentry.reddevs.io
            - traefik.docker.network=proxy
            - traefik.port=80
        expose:
            - "80"     
        restart: unless-stopped

    cron:
        image: sentry
        container_name: sentry_cron
        env_file: .env    
        labels:
            - traefik.enable=false  
        environment:
            - SENTRY_SECRET_KEY=${SECRET_KEY}
            - SENTRY_POSTGRES_HOST=${DB_HOST}
            - SENTRY_DB_USER=${DB_USER}
            - SENTRY_DB_PASSWORD=${DB_PASSWORD}
            - SENTRY_REDIS_HOST=${REDIS_HOST}
            - SENTRY_EMAIL_PORT=${SMTP_PORT}
            - SENTRY_EMAIL_HOST=${SMTP_HOST}
            - SENTRY_SERVER_EMAIL=${SMTP_EMAIL}
            - SENTRY_EMAIL_USER=${SMTP_USER}
            - SENTRY_EMAIL_PASSWORD=${SMTP_PASSWORD}
            - SENTRY_EMAIL_USE_TLS=${SMTP_USE_TLS}
        restart: unless-stopped
        command: "sentry run cron"

    worker:   
        image: sentry
        container_name: sentry_worker
        env_file: .env
        labels:
            - traefik.enable=false
        environment:
            - SENTRY_SECRET_KEY=${SECRET_KEY}
            - SENTRY_POSTGRES_HOST=${DB_HOST}
            - SENTRY_DB_USER=${DB_USER}
            - SENTRY_DB_PASSWORD=${DB_PASSWORD}
            - SENTRY_REDIS_HOST=${REDIS_HOST}
            - SENTRY_EMAIL_PORT=${SMTP_PORT}
            - SENTRY_EMAIL_HOST=${SMTP_HOST}
            - SENTRY_SERVER_EMAIL=${SMTP_EMAIL}
            - SENTRY_EMAIL_USER=${SMTP_USER}
            - SENTRY_EMAIL_PASSWORD=${SMTP_PASSWORD}
            - SENTRY_EMAIL_USE_TLS=${SMTP_USE_TLS}
        restart: unless-stopped
        command: "sentry run worker"

volumes:
    nginx_logs:
    postgres-data:

networks:
    reverse-proxy:
        external:
            name: proxy