version: "3.1"

services:
    sentry:
        image: sentry
        container_name: sentry_sentry
        env_file: .env
        ports:
            - "9000:9000"
        environment:
            SENTRY_SECRET_KEY: ${SECRET_KEY}
            SENTRY_POSTGRES_HOST: ${DB_HOST}
            SENTRY_DB_USER: ${DB_USER}
            SENTRY_DB_PASSWORD: ${DB_PASSWORD}
            SENTRY_REDIS_HOST: ${REDIS_HOST}
        
    cron:
        image: sentry
        container_name: sentry_cron
        env_file: .env      
        environment:
            SENTRY_SECRET_KEY: ${SECRET_KEY}
            SENTRY_POSTGRES_HOST: ${DB_HOST}
            SENTRY_DB_USER: ${DB_USER}
            SENTRY_DB_PASSWORD: ${DB_PASSWORD}
            SENTRY_REDIS_HOST: ${REDIS_HOST}
        command: "sentry run cron"

    worker:   
        image: sentry
        container_name: sentry_worker
        env_file: .env
        environment:
            SENTRY_SECRET_KEY: ${SECRET_KEY}
            SENTRY_POSTGRES_HOST: ${DB_HOST}
            SENTRY_DB_USER: ${DB_USER}
            SENTRY_DB_PASSWORD: ${DB_PASSWORD}
            SENTRY_REDIS_HOST: ${REDIS_HOST}
        command: "sentry run worker"

networks:
    default:
        external:
            name: franmakodatabases_default