version: "3.1"

services:
    redis:
        image: redis
    
    
networks:
    databases:
        external:
            name: franmakodatabases_default
    reverse-proxy:
        external:
            name: franmakoreverseproxy_reverse-proxy