version: "3.1"

services:
    sentry:
        image: sentry
        container_name: sentry_sentry
        env_file: .env
        ports:
            - "9000:9000"
        networks: 
            - databases
        environment:
            SENTRY_SECRET_KEY: ${SECRET_KEY}
            SENTRY_POSTGRES_HOST: ${DB_HOST}
            SENTRY_DB_USER: ${DB_USER}
            SENTRY_DB_PASSWORD: ${DB_PASSWORD}
            SENTRY_REDIS_HOST: ${REDIS_HOST}
        restart: always

    web:
        build: .
        container_name: sentry_web
        expose:
            - 80
            - 443
        networks: 
            - reverse-proxy
        environment:
            VIRTUAL_HOST: sentry.franmako.me
        restart: always
        
    cron:
        image: sentry
        container_name: sentry_cron
        env_file: .env   
        networks: 
            - databases   
        environment:
            SENTRY_SECRET_KEY: ${SECRET_KEY}
            SENTRY_POSTGRES_HOST: ${DB_HOST}
            SENTRY_DB_USER: ${DB_USER}
            SENTRY_DB_PASSWORD: ${DB_PASSWORD}
            SENTRY_REDIS_HOST: ${REDIS_HOST}
        restart: always
        command: "sentry run cron"

    worker:   
        image: sentry
        container_name: sentry_worker
        env_file: .env
        networks: 
            - databases
        environment:
            SENTRY_SECRET_KEY: ${SECRET_KEY}
            SENTRY_POSTGRES_HOST: ${DB_HOST}
            SENTRY_DB_USER: ${DB_USER}
            SENTRY_DB_PASSWORD: ${DB_PASSWORD}
            SENTRY_REDIS_HOST: ${REDIS_HOST}
        restart: always
        command: "sentry run worker"

networks:
    databases:
        external:
            name: franmakodatabases_default

    reverse-proxy:
        external:
            name: franmakoreverseproxy_reverse-proxy